// <auto-generated />
using System;
using DataAccess.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccess.Migrations
{
    [DbContext(typeof(PortalDbContext))]
    [Migration("20220920073107_20.09.2022")]
    partial class _20092022
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entities.Concreate.CV", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("CVs");
                });

            modelBuilder.Entity("Entities.Concreate.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CVId")
                        .HasColumnType("int");

                    b.Property<int>("CellPhone")
                        .HasColumnType("int");

                    b.Property<int>("CellPhone2")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("General")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Goal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HomePhone")
                        .HasColumnType("int");

                    b.Property<string>("MailAdress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalaryExp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkPhone")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CVId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("Entities.Concreate.Education", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AssociateCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssociateDepartment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("AssociateGPA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("AssociateGraduationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AssociateName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssociateNewDepartment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssociateNewSchool")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssociateState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CVId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HighGraduationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HighSchoolName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhDCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhDDepartment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PhDGPA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PhDGraduationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhDName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhDNewDepartment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhDNewSchool")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhDState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PrimaryGraduationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PrimarySchoolName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondarySchoolName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SeondaryGraduationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CVId");

                    b.ToTable("Educations");
                });

            modelBuilder.Entity("Entities.Concreate.EducationDegree", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DegreeCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DegreeDepartment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DegreeGPA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DegreeGraduationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DegreeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DegreeNewDepartment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DegreeNewSchool")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DegreeState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EducationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EducationId");

                    b.ToTable("EducationDegrees");
                });

            modelBuilder.Entity("Entities.Concreate.EducationPostDegree", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EducationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostgraduationCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostgraduationDepartment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PostgraduationGPA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PostgraduationGraduationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PostgraduationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostgraduationNewDepartment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostgraduationNewSchool")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostgraduationState")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EducationId");

                    b.ToTable("EducationPostDegrees");
                });

            modelBuilder.Entity("Entities.Concreate.General", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BornedCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BornedCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CVId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DriverLicense")
                        .HasColumnType("bit");

                    b.Property<string>("DriverLicenseType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Graduation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdentityNum")
                        .HasColumnType("int");

                    b.Property<string>("IdentityType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MartialStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nation")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CVId");

                    b.ToTable("Generals");
                });

            modelBuilder.Entity("Entities.Concreate.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CVId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExamResult")
                        .HasColumnType("int");

                    b.Property<string>("LanguageExam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LanguageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReadingLvl")
                        .HasColumnType("int");

                    b.Property<int>("SpeakingLvl")
                        .HasColumnType("int");

                    b.Property<int>("UnderstandingLvl")
                        .HasColumnType("int");

                    b.Property<int>("WritingLvl")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CVId");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("Entities.Concreate.Other", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CVId")
                        .HasColumnType("int");

                    b.Property<bool>("Cigaratte")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DefermentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Interests")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberGNO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MilitaryStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TravelContinents")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CVId");

                    b.ToTable("Others");
                });

            modelBuilder.Entity("Entities.Concreate.PostWork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CVId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyDepartment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CompanyLeavingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CompanyLeavingReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyMission")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyPosition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CompanySalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CompanyStartingDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("CompanyStillWorking")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CVId");

                    b.ToTable("PostWorks");
                });

            modelBuilder.Entity("Entities.Concreate.Referance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CVId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferanceEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferanceFoundation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferanceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReferancePhoneNumber")
                        .HasColumnType("int");

                    b.Property<int>("ReferancePhoneNumber2")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CVId");

                    b.ToTable("Referances");
                });

            modelBuilder.Entity("Entities.Concreate.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CVId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SkillName")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CVId");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("Entities.Concreate.Contact", b =>
                {
                    b.HasOne("Entities.Concreate.CV", "CVInfo")
                        .WithMany("ContactInfos")
                        .HasForeignKey("CVId");

                    b.Navigation("CVInfo");
                });

            modelBuilder.Entity("Entities.Concreate.Education", b =>
                {
                    b.HasOne("Entities.Concreate.CV", "CVInfo")
                        .WithMany("EducationInfos")
                        .HasForeignKey("CVId");

                    b.Navigation("CVInfo");
                });

            modelBuilder.Entity("Entities.Concreate.EducationDegree", b =>
                {
                    b.HasOne("Entities.Concreate.Education", "Education")
                        .WithMany("EducationDegreeInfos")
                        .HasForeignKey("EducationId");

                    b.Navigation("Education");
                });

            modelBuilder.Entity("Entities.Concreate.EducationPostDegree", b =>
                {
                    b.HasOne("Entities.Concreate.Education", "Education")
                        .WithMany("EducationPostDegreeInfos")
                        .HasForeignKey("EducationId");

                    b.Navigation("Education");
                });

            modelBuilder.Entity("Entities.Concreate.General", b =>
                {
                    b.HasOne("Entities.Concreate.CV", "CVInfo")
                        .WithMany("GeneralInfos")
                        .HasForeignKey("CVId");

                    b.Navigation("CVInfo");
                });

            modelBuilder.Entity("Entities.Concreate.Language", b =>
                {
                    b.HasOne("Entities.Concreate.CV", "CVInfo")
                        .WithMany("LanguageInfos")
                        .HasForeignKey("CVId");

                    b.Navigation("CVInfo");
                });

            modelBuilder.Entity("Entities.Concreate.Other", b =>
                {
                    b.HasOne("Entities.Concreate.CV", "CVInfo")
                        .WithMany("OtherInfos")
                        .HasForeignKey("CVId");

                    b.Navigation("CVInfo");
                });

            modelBuilder.Entity("Entities.Concreate.PostWork", b =>
                {
                    b.HasOne("Entities.Concreate.CV", "CVInfo")
                        .WithMany("PostWorkInfos")
                        .HasForeignKey("CVId");

                    b.Navigation("CVInfo");
                });

            modelBuilder.Entity("Entities.Concreate.Referance", b =>
                {
                    b.HasOne("Entities.Concreate.CV", "CVInfo")
                        .WithMany("ReferanceInfos")
                        .HasForeignKey("CVId");

                    b.Navigation("CVInfo");
                });

            modelBuilder.Entity("Entities.Concreate.Skill", b =>
                {
                    b.HasOne("Entities.Concreate.CV", "CVInfo")
                        .WithMany("SkillInfos")
                        .HasForeignKey("CVId");

                    b.Navigation("CVInfo");
                });

            modelBuilder.Entity("Entities.Concreate.CV", b =>
                {
                    b.Navigation("ContactInfos");

                    b.Navigation("EducationInfos");

                    b.Navigation("GeneralInfos");

                    b.Navigation("LanguageInfos");

                    b.Navigation("OtherInfos");

                    b.Navigation("PostWorkInfos");

                    b.Navigation("ReferanceInfos");

                    b.Navigation("SkillInfos");
                });

            modelBuilder.Entity("Entities.Concreate.Education", b =>
                {
                    b.Navigation("EducationDegreeInfos");

                    b.Navigation("EducationPostDegreeInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
